import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google"; 
import "./styles/globals.scss";


const bebasNeue = Bebas_Neue({ 
  weight: ['400'],
  subsets: ["latin"],
  variable: "--font-bebas",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bebasNeue.variable}`}>
      <body>
        {children}
      </body>
    </html>
  );
}